# Generated by Django 3.1.4 on 2020-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_auto_20201217_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/users/avatar'),
        ),
    ]
