# Generated by Django 3.1.4 on 2020-12-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('word_en', models.CharField(max_length=30)),
                ('word_ru', models.CharField(max_length=30)),
                ('text_en', models.CharField(max_length=3000)),
                ('text_ru', models.CharField(max_length=3000)),
                ('audio_en', models.CharField(max_length=100)),
                ('audio_ru', models.CharField(max_length=100)),
                ('wiki_en', models.CharField(max_length=100)),
                ('wiki_ru', models.CharField(max_length=100)),
            ],
        ),
    ]
