# Generated by Django 3.1.4 on 2020-12-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio_ru',
        ),
        migrations.RemoveField(
            model_name='word',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='word',
            name='wiki_ru',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_ru',
        ),
    ]
