# Generated by Django 3.1.4 on 2020-12-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20201210_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='text_ru',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='wiki_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word_ru',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
