# Generated by Django 3.1.4 on 2020-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20201211_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_en',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio_ru',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='text_ru',
            field=models.TextField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='word',
            name='wiki_en',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='wiki_ru',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_ru',
            field=models.CharField(max_length=100),
        ),
    ]
