# Generated by Django 3.1.4 on 2020-12-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_historyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyword',
            options={'ordering': ['-date_of_add']},
        ),
    ]
